apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog-service.fullname" . }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "catalog-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
