 # Define el espacio de nombres donde vivir√°n todos los servicios.
apiVersion: v1
kind: Namespace
metadata:
  name: videoclub-pro
  labels:
    environment: pro
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline