# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: metrics-server
#   namespace: kube-system
# spec:
#   template:
#     spec:
#       containers:
#         - name: metrics-server
#           args:
#             - --cert-dir=/tmp
#             - --secure-port=4443
#             - --kubelet-insecure-tls  # necesario en entornos locales
#             - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
#             - --metric-resolution=15s