apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: videoclub-dev
resources:
  - ../../base
  - ingress.yaml

nameSuffix: -dev

patches:
  - path: configmap-patch.yaml
  - path: secrets-patch.yaml
