apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: videoclub-int
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

nameSuffix: -int

patches:
  - path: configmap-patch.yaml
  - path: secrets-patch.yaml
