eureka:
  instance:
    hostname: ${HOSTNAME}
  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    org.springframework: INFO   # o WARN
