server:
  port: ${DISCOVERY_SERVICE_PORT:8761}

spring:
  application:
    name: discovery-service
  security:
    user:
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASS:secret}
      roles: SYSTEM

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USER:admin}:${EUREKA_PASS:secret}@localhost:8761/eureka/}
  server:
    # enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: ${HOSTNAME:localhost}   # o 192.168.1.78
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
