apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "discovery-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "discovery-service.name" . }}
    spec:
      containers:
        - name: discovery-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
