apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-service.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "discovery-service.name" . }}
  ports:
    - port: 8761
      targetPort: 8761
