apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-service.fullname" . }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "inventory-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
