apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap/configmap.yaml
  - ingress-class.yaml
  - secrets/secrets.yaml   # añade esta línea
  - databases/
  - messaging/
  - services/
  - network/network-policies.yaml
  - hpa/
  - ingress/ingress.yaml
