image:
  repository: javixulobo/videoclub-catalog-service-dev
  tag: v0.0.2
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8083

serviceAccount:
  create: true
  name: ""

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 640Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_CLOUD_CONFIG_ENABLED
    value: "false"
  - name: SERVER_PORT
    value: "8083"
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: http://discovery-service-dev:8761/eureka/
