apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: clientes_db
            - name: MYSQL_USER
              value: customer_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-db-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-db-secret
                  key: root_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: customer-db-pvc
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-db-secret
  
type: Opaque
stringData:
  password: "customer123"
  root_password: "root123"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-db-pvc
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  
spec:
  selector:
    app: customer-db
  ports:
    - port: 3306
      targetPort: 3306
