apiVersion: v1
kind: ConfigMap
metadata:
  name: videoclub-global-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  EUREKA_URL: "http://discovery-service-dev:8761/eureka/"
  CONFIG_URL: "http://config-service-dev:8888"
  LOGGING_LEVEL_ROOT: "DEBUG"
